export const item = {
  caNoticeId: 100066869,
  noticeId: 100174450,
  procedureId: 100045278,
  noticeNo: "CAN1031498",
  sysNoticeTypeId: 3,
  sysNoticeState: {
    id: 2,
    text: "Publicat",
    localeKey: null,
  },
  sysProcedureState: {
    id: 5,
    text: "Atribuita",
    localeKey: null,
  },
  contractingAuthorityNameAndFN:
    "RO1590120 - REGIA NATIONALA A PADURILOR - ROMSILVA RA",
  contractTitle:
    "servicii de exploatare masa lemnoasa si transport lemn fasonat DSSV-I",
  sysAcquisitionContractType: {
    id: 2,
    text: "Servicii",
    localeKey: null,
  },
  sysProcedureType: {
    id: 1,
    text: "Licitatie deschisa",
    localeKey: null,
  },
  sysContractAssigmentType: {
    id: 1,
    text: "Contract de achizitii publice",
    localeKey: null,
  },
  cpvCodeAndName: "77211100-3 - Servicii de exploatare forestiera (Rev.2)",
  ronContractValue: 12130675.84,
  isOnline: true,
  noticeStateDate: "2020-04-04T01:54:35+03:00",
  minTenderReceiptDeadline: null,
  maxTenderReceiptDeadline: null,
  errataNo: 0,
  versionNo: null,
  sysNoticeVersionId: 2,
  tenderReceiptDeadlineExport: null,
  estimatedValueExport: "12130675,84 RON",
  highestOfferValue: 0.0,
  lowestOfferValue: 0.0,
  hasSubsequentContracts: false,
  isUtility: false,
  isPPP: false,
  currencyCode: "RON",
}

export const notice = {
  isUtilityContract: false,
  caNoticeEdit_New: {
    publicationDetailsModel: {
      caPublicationDate: "2018-12-10T09:24:07+02:00",
      publicationDate: "2018-07-18T13:22:23+03:00",
      jouePublicationNumber: "",
      noticeNo: "CN1002546",
    },
    section0_New: {
      sentToJOUE: false,
      tedNoticeNo: null,
      completeTedModel: {
        caNoticeId: 0,
        ojeuNoticeNoYear: null,
        ojeuNoticeNoSecondPart: null,
        ojeuNoticeNoThirdPart: null,
        ojeuNoticeDate: null,
      },
      canEdit: false,
      caNoticeId: 0,
      sectionName: null,
      sectionCode: null,
      noticePreviousPublication: null,
    },
    section1_New: {
      section1_1: {
        caAddress: {
          noticeId: 100114690,
          officialName:
            "SPITALUL CLINIC JUDETEAN DE URGENTA SF. APOSTOL ANDREI",
          address: "Strada: Tomis, nr. 145",
          city: "Constanta",
          cityItem: null,
          postalCode: "900591",
          postalCodeItem: null,
          countryID: 1,
          country: "Romania",
          countryItem: {
            id: 1,
            text: "Romania",
            localeKey: "RO",
          },
          county: null,
          email: "xxx@xxx.ro",
          phone: "+40 xxxxxx",
          fax: "+40 xxxxxx",
          contactPoints: "xxx xxx",
          attentionTo: "xxx xxx",
          caMainAddressUrl: "www.spitalulconstanta.ro",
          buyerProfileUrl: "www.e-licitatie.ro",
          nutsCodeID: 28,
          nutsCode:
            "System.Data.Entity.DynamicProxies.NUTSCode_547C7532A1C13D2DD8DABA397AFE64934E6300F80287E631C82996E76CE950EB",
          nutsCodeItem: {
            id: 28,
            text: "RO223 Constanta",
            localeKey: null,
          },
          contactPerson: "xxx xxx",
          internetAddressesUrl: ["www.spitalulconstanta.ro"],
          electronicInfoAccessUrl: null,
          electronicDocumentsSendingUrl: null,
          isSME: false,
          sysNoticeEntityTypeID: 1,
          noticeEntityAddressId: 100437403,
          entityId: 560,
          entityItem: null,
          isPublishingAgreed: null,
          nationalIDNumber: "4301103",
        },
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      section1_2_New: {
        isCommonProcurement: false,
        commonProcurementLaw: null,
        isAwardedByCentralAcquisitionOrgan: false,
        otherCANoticeAdresses: [],
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      section1_4_New: {
        caTypeId: 18,
        caType: {
          id: 18,
          text: "Organism de drept public",
          localeKey:
            "Common.Clasiff.ContractingAuthorityType.BodyGuvernedByLow",
        },
        ifOthersThenSpecify: null,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      section1_5: {
        mainActivityId: 6,
        mainActivity: {
          id: 6,
          text: "Sanatate",
          localeKey: "Common.Clasiff.ActivityType.Health",
        },
        ifOthersThenSpecify: null,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
    },
    section2_New: {
      section2_1_New: {
        contractTitle:
          "Furnizarea si instalarea urmatoarelor echipamente medicale: Videolaringoscop pentru sectia ATI Adulti,  Trusa de chirurgie laparoscopica si instrumentar pentru Urologie, Spirometre pentru Explorari Functionale, Ecograf cu trei sonde pentru Explorari functionale si Electrocardiografe portabile/5 Loturi",
        referenceNumber: "26932/09.07.2018",
        mainCPVCode: {
          id: 12677,
          text: "Echipamente medicale (Rev.2)",
          localeKey: "33100000-1",
        },
        sysAcquisitionContractType: {
          id: 1,
          text: "Furnizare",
          localeKey: "Common.Clasiff.SysAcquisitionContractType.Supply",
        },
        shortDescription:
          "Furnizarea si instalarea urmatoarelor echipamente medicale: videolaringoscop pentru sectia ATI Adulti/lot 1, Trusa de chirurgie laparoscopica si instrumentar pentru Urologie/Lot 2, Spirometre pentru Explorari Functionale/Lot 3, Ecograf cu trei sonde pentru Explorari functionale/ Lot 4 si Electrocardiografe portabile/Lot 5.\n\nValoarea contractului de furnizare pentru fiecare LOT in parte:\nLot 1 - videolaringoscop - 50672,26 Lei\nLot 2 - trusa de chirurgie laparoscopica si instrumentar pentru Urologie - 322100,84 Lei \nLot 3 - spirometre pentru Explorari Functionale/2 buc - 20588,23Lei\nLot 4 - ecograf cu trei sonde pentru Explorari Functionale - 168319,32 Lei \nLot 5 - electrocardiografe portabile/6 buc - 72184,86Lei \nValoarea totala a celor 5 loturi este de 633865,51 Lei\nDetaliile fiecarui lot se regasesc in Caietul de sarcini.\nGarantia de participare reprezinta 1% din valoarea fara TVA pentru fiecare LOT ofertat\nTermenul limita pana la care se pot solicita clarificari la documentatia de atribuire: cu 13 zile inainte de data limita de depunere a ofertelor . In conformitate cu prevederile art.161 din legea 98/2016, autoritatea contractanta va raspunde in mod clar si complet solicitarilor de clarificare/informtiilor suplimentare in legatura cu documentatia de atribuire in a 10 a zi inainte de termenul limita stabilit pentru depunerea ofertelor in anuntul de participare",
        hasLots: true,
        numberOfLots: null,
        shouldShowSection217: true,
        totalAcquisitionValue: 477200.0,
        totalRONAcquisitionValueForPAAP: 477200.0,
        lowestOffer: 0.0,
        highestOffer: 0.0,
        currency: {
          id: 1,
          text: "Leu",
          localeKey: "RON",
        },
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      section2_2_New: {
        showPublishingAgreedSection: false,
        previousPublication: true,
        descriptionList: [
          {
            noticeLotID: 100188111,
            contractTitle: "Videolaringoscop pentru ATI Adulti",
            lotNumber: "1",
            mainCPVCodes: {
              id: 12677,
              text: "33100000-1 Echipamente medicale (Rev.2)",
              localeKey: null,
            },
            secondaryCPVCodes: [],
            nutsCode: {
              id: 28,
              text: "RO223 Constanta",
              localeKey: null,
            },
            mainLocation: "SCJU Constanta",
            shortDescription:
              "Videolaringoscop pentru ATI Adulti/1 buc. Descrierea lotului se regaseste in Caietul de sarcini",
            noticeAwardCriteriaList: [
              {
                noticeAwardCriteriaID: 100035892,
                noticeAwardCriteriaName: "Pretul ofertei",
                noticeAwardCriteriaDescription: "Componenta financiara",
                noticeAwardCriteriaWeight: 80.0,
                noticeAwardCriteriaOrder: 1,
                algorithmDescription:
                  "Punctajul se acorda astfel: a) Pentru cel mai scazut dintre preturi se acorda punctajul maxim alocat; b) Pentru celelalte preturi ofertate punctajul P(n) se calculeaza proportional, astfel: P(n) = (Pret minim ofertat / Pret n) x punctaj maxim alocat.",
                isElectronicCriteria: false,
                isPriceCriteria: true,
                isFrameworkAgreementCriteria: false,
                directProportional: null,
                sysAwardCriteriaTypeId: null,
              },
              {
                noticeAwardCriteriaID: 100035891,
                noticeAwardCriteriaName:
                  "Componenta tehnica: temenele de garantie acordate: maxim 36 luni ptr echipament si maxim 24 luni ptr accesorii sau minim 24  luni ptr echipament si minim 12 luni ptr accesorii",
                noticeAwardCriteriaDescription:
                  "Termene de garantie acordate:   maxim 36 de luni ptr echipament si maxim 24 luni ptr accesoriile acestuia  -  punctaj maxim acordat: 20 de puncte\n Termene de garantie acordate:   minim 24 de luni ptr echipament si minim 12 luni ptr accesoriile acestuia - punctaj minim acordat: 10 puncte.\nPentru acordarea altor termene de garantie  se va aplica urmatorul algoritm de calcul:",
                noticeAwardCriteriaWeight: 20.0,
                noticeAwardCriteriaOrder: 2,
                algorithmDescription:
                  "Formula: P2  = (Gf   -  Gm)/(GM -  Gm) x (20 - 10)\n\nGf   – garantia furnizorului, \nGm – garantia minima,\nGM – garantia maxima,\n20 – punctajul maxim acordat pentru termenul maxim de garantie,\n10 – punctajul minim acordat pentru termenul de minim de garantie",
                isElectronicCriteria: null,
                isPriceCriteria: null,
                isFrameworkAgreementCriteria: null,
                directProportional: null,
                sysAwardCriteriaTypeId: null,
              },
            ],
            hasOptions: false,
            optionsDescription: null,
            isEUFunded: false,
            euProject: null,
            supplementaryInformation:
              "Valoarea totala a lotului este de 50672,26. Garantia de participare reprezinta 1% din valoarea totala a lotului.",
            monthDuration: 6,
            dayDuration: null,
            startDate: null,
            completionDate: null,
            showSysAwardCriteriaType: true,
            sysAwardCriteriaTypeId: 2,
            sysAwardCriteriaType: {
              id: 2,
              text: "Cel mai bun raport calitate – pret",
              localeKey: null,
            },
            sysEuropeanFundId: null,
            sysEuropeanFund: null,
            sysFinancingTypeId: null,
            sysFinancingType: {
              id: 2,
              text: "Fonduri bugetare",
              localeKey: null,
            },
            communityProgramReference: null,
            estimatedValue: 50672.26,
            minEstimatedValue: null,
            maxEstimatedValue: null,
            currency: {
              id: 1,
              text: "Leu",
              localeKey: null,
            },
            lotInfo: "Anulat",
          },
          {
            noticeLotID: 100188113,
            contractTitle: "Electrocardiografe portabile /6 buc",
            lotNumber: "5",
            mainCPVCodes: {
              id: 12677,
              text: "33100000-1 Echipamente medicale (Rev.2)",
              localeKey: null,
            },
            secondaryCPVCodes: [],
            nutsCode: {
              id: 28,
              text: "RO223 Constanta",
              localeKey: null,
            },
            mainLocation: "SCJU Constanta",
            shortDescription:
              "Electrocardiografe portabile /6 buc. Descrierea lotului se regaseste in Caietul de sarcini",
            noticeAwardCriteriaList: [
              {
                noticeAwardCriteriaID: 100035896,
                noticeAwardCriteriaName: "Pretul ofertei",
                noticeAwardCriteriaDescription: "Componenta financiara",
                noticeAwardCriteriaWeight: 80.0,
                noticeAwardCriteriaOrder: 1,
                algorithmDescription:
                  "Punctajul se acorda astfel: a) Pentru cel mai scazut dintre preturi se acorda punctajul maxim alocat; b) Pentru celelalte preturi ofertate punctajul P(n) se calculeaza proportional, astfel: P(n) = (Pret minim ofertat / Pret n) x punctaj maxim alocat.",
                isElectronicCriteria: false,
                isPriceCriteria: true,
                isFrameworkAgreementCriteria: false,
                directProportional: null,
                sysAwardCriteriaTypeId: null,
              },
              {
                noticeAwardCriteriaID: 100035895,
                noticeAwardCriteriaName:
                  "Componenta tehnica: temenele de garantie acordate: maxim 36 luni ptr echipament si maxim 24 luni ptr accesorii sau minim 24  luni ptr echipament si minim 12 luni ptr accesorii",
                noticeAwardCriteriaDescription:
                  "Termene de garantie acordate:  maxim 36 de luni ptr echipament si maxim 24 luni ptr accesoriile acestuia  - punctaj maxim acordat: 20 de puncte.\n Termene de garantie acordate: minim 24 de luni ptr echipament si minim 12 luni ptr accesoriile acestuia - punctaj minim acordat: 10 puncte.\nPentru acordarea altor termene de garantie  se va aplica urmatorul algoritm de calcul",
                noticeAwardCriteriaWeight: 20.0,
                noticeAwardCriteriaOrder: 2,
                algorithmDescription:
                  "Formula: P2  = (Gf   -  Gm)/(GM -  Gm) x (20 - 10)\n\nGf   – garantia furnizorului, \nGm – garantia minima,\nGM – garantia maxima,\n20 – punctajul maxim acordat pentru termenul maxim de garantie,\n10 – punctajul minim acordat pentru termenul de minim de garantie",
                isElectronicCriteria: null,
                isPriceCriteria: null,
                isFrameworkAgreementCriteria: null,
                directProportional: null,
                sysAwardCriteriaTypeId: null,
              },
            ],
            hasOptions: false,
            optionsDescription: null,
            isEUFunded: false,
            euProject: null,
            supplementaryInformation:
              "Valoarea totala a lotului este de 72184,86. Garantia de participare reprezinta 1% din valoarea totala a lotului.",
            monthDuration: 6,
            dayDuration: null,
            startDate: null,
            completionDate: null,
            showSysAwardCriteriaType: true,
            sysAwardCriteriaTypeId: 2,
            sysAwardCriteriaType: {
              id: 2,
              text: "Cel mai bun raport calitate – pret",
              localeKey: null,
            },
            sysEuropeanFundId: null,
            sysEuropeanFund: null,
            sysFinancingTypeId: null,
            sysFinancingType: {
              id: 2,
              text: "Fonduri bugetare",
              localeKey: null,
            },
            communityProgramReference: null,
            estimatedValue: 72184.86,
            minEstimatedValue: null,
            maxEstimatedValue: null,
            currency: {
              id: 1,
              text: "Leu",
              localeKey: null,
            },
            lotInfo: "Anulat",
          },
        ],
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
    },
    section4_New: {
      section4_1_New: {
        sysProcedureTypeId: 1,
        sysProcedureType: {
          id: 1,
          text: "Licitatie deschisa",
          localeKey: null,
        },
        isAcceleratedProcedure: null,
        acceleratedProcedureJustification: "",
        sysContractAssigmentTypeId: 1,
        sysContractAssigmentType: null,
        hasElectronicAuction: false,
        hasGpaAgreement: false,
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      section4_2_New: {
        hasPreviousPublicationNotice: false,
        tedModel: null,
        previousPublicationNoticeNumber: "",
        isCeasingDynamicAquisitions: false,
        isCACeasingSendingInvitations: false,
        canEdit: null,
        updateTed: null,
        caNoticeId: 0,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
    },
    section5: {
      contractLotList: [],
      cancelledLotList: [
        {
          caNoticeId: 100037160,
          noticeLot: {
            noticeLotId: 100188111,
            noticeContractObjectId: 100045975,
            no: "1",
            title: "Videolaringoscop pentru ATI Adulti",
            value: 50672.26,
            procedureLotId: 100045099,
          },
          sysCancellationReason: null,
          cancellationReasonComment:
            'Au fost depuse numai oferte inacceptabile si/sau neconforme, oferta neconforma cf art 137, alin 3, lit a) HG/395/2016 "oferta nu satisface in mod corespunzator cerintele caietului de sarcini"',
          cancellationDate: "2018-11-02T00:00:00+02:00",
        },
        {
          caNoticeId: 100037160,
          noticeLot: {
            noticeLotId: 100188113,
            noticeContractObjectId: 100045975,
            no: "5",
            title: "Electrocardiografe portabile /6 buc",
            value: 72184.86,
            procedureLotId: 100045101,
          },
          sysCancellationReason: null,
          cancellationReasonComment:
            'Au fost depuse numai oferte inacceptabile si/sau neconforme, Oferta neconforma cf art 137, alin 3, lit a) din HG/395/2016 intrucat "nu satisface in mod corespunzator cerintele Caietului de sarcini"',
          cancellationDate: "2018-11-02T00:00:00+02:00",
        },
        {
          caNoticeId: 100037160,
          noticeLot: {
            noticeLotId: 100188115,
            noticeContractObjectId: 100045975,
            no: "3",
            title: "Spirometre pentru Explorari Functionale/2 buc",
            value: 20588.23,
            procedureLotId: 100045103,
          },
          sysCancellationReason: null,
          cancellationReasonComment:
            "Au fost depuse numai oferte inacceptabile si/sau neconforme, Oferte inacceptabile cf art 134, al 5 din HG/395/2016, ofertantii nu au raspuns in termenul legal acordat la solicitarile de clarificari",
          cancellationDate: "2018-11-02T00:00:00+02:00",
        },
      ],
      section52A: {
        caNoticeId: 100037160,
        currency: {
          id: 1,
          text: "RON",
          localeKey: "RON",
        },
      },
    },
    section6_New: {
      section6_3_New: {
        supplementaryInformation:
          'In situatia in care doi sau mai multi ofertanti situati pe primul loc au acelasi pret, autoritatea contractanta va solicita reofertarea prin intermediul SEAP si va solicita ofertantilor aflati in aceasta situatie sa transmita in format ELECTRONIC in SEAP o noua propunere financiara. Ofertantul care va obtine punctajul cel mai mare in urma aplicarii criteriului "cel mai bun raport calitate - pret" va fi declarant castigator,in situatia in care preturile sunt la egalitate, autoritatea contractanta va solicita reofertare conform pasilor expusi anterior pana cand departajarea va putea fi posibila.',
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      section6_4_1_New: {
        disputeHandleOrganization: {
          noticeId: 100114690,
          officialName: "Consiliul National de Solutionare a Contestatiilor",
          address: "Str. Stavropoleos nr. 6, sector 3",
          city: "Bucuresti",
          cityItem: null,
          postalCode: "030084",
          postalCodeItem: null,
          countryID: 1,
          country: "Romania",
          countryItem: {
            id: 1,
            text: "Romania",
            localeKey: "RO",
          },
          county: null,
          email: "xxx@xxx.ro",
          phone: "+40 xxx",
          fax: "+40 xxx / +40 xxx",
          contactPoints: null,
          attentionTo: null,
          caMainAddressUrl: "www.cnsc.ro",
          buyerProfileUrl: "www.e-licitatie.ro",
          nutsCodeID: 42,
          nutsCode:
            "System.Data.Entity.DynamicProxies.NUTSCode_547C7532A1C13D2DD8DABA397AFE64934E6300F80287E631C82996E76CE950EB",
          nutsCodeItem: {
            id: 42,
            text: "RO321 Bucuresti",
            localeKey: null,
          },
          contactPerson: null,
          internetAddressesUrl: ["www.cnsc.ro"],
          electronicInfoAccessUrl: null,
          electronicDocumentsSendingUrl: null,
          isSME: false,
          sysNoticeEntityTypeID: 11,
          noticeEntityAddressId: 100437404,
          entityId: null,
          entityItem: null,
          isPublishingAgreed: null,
          nationalIDNumber: null,
        },
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      section6_4_2_New: null,
      section6_4_3_New: {
        disputeProcedure:
          "Termenele de exercitare a cailor de atac sunt cele prevazute in Legea nr 101/2016",
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      section6_4_4_New: {
        disputeInformationService: {
          noticeId: 100114690,
          officialName: "Oficiul juridic",
          address: "B dul Tomis, nr 145",
          city: "Constanta",
          cityItem: {
            id: 3181,
            text: "Constanta",
            localeKey: "",
          },
          postalCode: "900591",
          postalCodeItem: null,
          countryID: 1,
          country: "Romania",
          countryItem: {
            id: 1,
            text: "Romania",
            localeKey: "RO",
          },
          county: null,
          email: "xxxx@xxxx.ro",
          phone: "+40 xxxx",
          fax: "+40 xxxx",
          contactPoints: null,
          attentionTo: null,
          caMainAddressUrl: "www.spitalulconstanta.ro",
          buyerProfileUrl: "www.e-licitatie.ro",
          nutsCodeID: 28,
          nutsCode:
            "System.Data.Entity.DynamicProxies.NUTSCode_547C7532A1C13D2DD8DABA397AFE64934E6300F80287E631C82996E76CE950EB",
          nutsCodeItem: {
            id: 28,
            text: "RO223 Constanta",
            localeKey: null,
          },
          contactPerson: null,
          internetAddressesUrl: ["www.spitalulconstanta.ro"],
          electronicInfoAccessUrl: null,
          electronicDocumentsSendingUrl: null,
          isSME: false,
          sysNoticeEntityTypeID: 13,
          noticeEntityAddressId: 100437405,
          entityId: null,
          entityItem: null,
          isPublishingAgreed: null,
          nationalIDNumber: null,
        },
        canEdit: false,
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
      shouldShowSection6_4_567: false,
      section6_4_567_New: null,
      section6_5_New: {
        noticeSendDate: "2018-12-10T09:24:07+02:00",
        caNoticeId: 100037160,
        sectionName: null,
        sectionCode: null,
        noticePreviousPublication: null,
      },
    },
    annexD_New: {
      noOfferForOpenProcedure: null,
      noOfferForRestrictedProcedure: null,
      bargainPurchase: null,
      noticeID: null,
      areProductsResearchAndStudy: false,
      isForceMajeure: false,
      isSupplementaryServiceCompliantOrdered: false,
      isNewServiceARepetition: false,
      isAssignedToAProjectContestWinner: false,
      areProductsStockExchangeListed: false,
      isSupplierCeasingOperations: false,
      isSuppliedFromBankruptcy: false,
      sysReasonForUniqueOfferer: null,
      isAcquisitionDirectiveCompliant: false,
      explanation: null,
      canEdit: false,
      unawardedSysNoticeType: null,
      unawardedSysNoticeTypeId: null,
      unawardedNoticeNo: null,
      caNoticeId: 100037160,
      sectionName: null,
      sectionCode: null,
      noticePreviousPublication: null,
    },
  },
  caNoticeEdit_New_U: null,
  cNoticeId: 100005147,
  isView: true,
  errorList: [],
  hasErrors: false,
  title:
    "Furnizarea si instalarea urmatoarelor echipamente medicale: Videolaringoscop pentru sectia ATI Adulti,  Trusa de chirurgie laparoscopica si instrumentar pentru Urologie, Spirometre pentru Explorari Functionale, Ecograf cu trei sonde pentru Explorari functionale si Electrocardiografe portabile/5 Loturi",
  caNoticeID: 100037160,
  isPPP: false,
  noticeID: 100114690,
  previousPublicationNoticeID: 100045478,
  previousPublicationNoticeNumber: null,
  sysContractAssignmentTypeID: 1,
  sysNoticeState: {
    id: 2,
    text: "Publicat",
    localeKey: "Common.Clasiff.SysNoticeState.Published",
  },
  sysNoticeType: {
    id: 3,
    text: "Anunt de atribuire",
    localeKey: "Common.Clasiff.SysNoticeType.ContractAwardNotice",
  },
  prevPubSysNoticeType: {
    id: 2,
    text: "Anunt de participare",
    localeKey: "Common.Clasiff.SysNoticeType.ContractNotice",
  },
  contractingAuthorityType: {
    id: 18,
    text: "Organism de drept public",
    localeKey: "Common.Clasiff.ContractingAuthorityType.BodyGuvernedByLow",
  },
  sysNoticeVersion: {
    id: 2,
    text: "Formulare in format > 2016",
    localeKey: "Common.Clasiff.SysNoticeVersion.NewFormat",
  },
  procedureId: 100012670,
  isOnlineProcedure: false,
  isLeProcedure: false,
  paapModel: {
    paapDetailName: "",
    procedureType: "",
    uniqueIdentificationCode: null,
    acquisitionValue: 0.0,
    contractAcquisitionValue: 477200.0,
    currency: "RON",
    paapDetailId: 0,
    paapName: "",
    paapYear: null,
    paapVersion: null,
    sysFinancingType: null,
    cpvCode: null,
    localStrategyObjective: null,
    isOnline: null,
    responsibleUnit: null,
    valueLeftToAllocateRON: null,
  },
  paapSpentValue: 0.0,
  entityId: 560,
  legislationType: {
    id: 3,
    text: "Legea nr. 98/23.05.2016",
    localeKey: "Common.Clasiff.SysLegislationType.LAW_98_2016",
  },
  procedureType: {
    id: 1,
    text: "Licitatie deschisa",
    localeKey: null,
  },
  parentCaNoticeId: null,
  parentSysNoticeVersionId: null,
  isCorrecting: false,
  isCompleting: false,
  isModifNotice: false,
  versionNumber: null,
  ackDocs: [],
  noticeNumber: "CAN1008830",
  createDate: "0001-01-01T00:00:00+02:00",
  isCA: false,
  acAssignedUser: null,
  procedureHasLots: false,
  publicationDate: "2018-12-10T09:24:07+02:00",
  sentToJOUE: false,
  tedNoticeNo: null,
  ackDocsCount: 0,
  initState: null,
  actions: {
    canVerify: false,
    canPreview: false,
    canDelete: false,
    canAssociateUser: false,
    canGoBack: false,
    canPublish: false,
    canPrint: true,
    canCorrect: false,
    canComplete: false,
    canEdit: false,
    canEditPaap: false,
    canEditTed: false,
    canAddCancelledLots: false,
    canGetCancelledLots: false,
    canDeleteCancelledLots: false,
    canGenerateContracts: false,
    canGenerateOnPublish: false,
    canEditCurrency: false,
    canGenerateAwardingSection: false,
    canAddNewContract: false,
    canAddSubsequentContract: false,
    canAddFrameworkAgreementContract: false,
    canAddManualErrata: false,
  },
  conditions: {
    hasPP: true,
    isOnline: true,
    hasEA: false,
    isFrameworkAgreement: false,
    isUtility: false,
    hasVersions: false,
    hasErrata: false,
    hasAckDocuments: false,
    hasAnnexD: false,
    hasLots: true,
    hasCancelledLotsSection: true,
    hasAwardedLotsSection: true,
    showRONColumnsOnContractList: false,
  },
}

export const contracts = {
  total: 2,
  items: [
    {
      caNoticeContractId: 100063850,
      contractId: null,
      caNoticeId: 100037160,
      noticeNo: "CAN1008830",
      contractNo: "46218",
      contractDate: "2018-11-22T00:00:00+02:00",
      contractTitle: "Contract de furnizare",
      winnerCaption: "KARL STORZ ENDOSCOPIA ROMANIA",
      winner: {
        id: 100068340,
        caNoticeId: 100037160,
        name: "KARL STORZ ENDOSCOPIA ROMANIA",
        fiscalNumber: "RO 22505268",
        noticeEntityAddressId: 100437472,
        entityId: 31248,
        isSME: null,
        address: {
          noticeId: null,
          officialName: "KARL STORZ ENDOSCOPIA ROMANIA",
          address: "Strada Colorian Anton, prof. dr., Nr. 74, Sector: 4",
          city: "Bucuresti",
          cityItem: {
            id: 1779,
            text: "Bucuresti",
            localeKey: "",
          },
          postalCode: "041393",
          postalCodeItem: null,
          countryID: 1,
          country: "Romania",
          countryItem: {
            id: 1,
            text: "Romania",
            localeKey: "RO",
          },
          county: {
            id: 4,
            text: "Bucuresti",
            localeKey: "B",
          },
          email: "xxx.xxx@xxx.xxx; zzz.zzz@zzz.com",
          phone: "+40 xxxxxx",
          fax: "+40 xxxxxx",
          contactPoints: null,
          attentionTo: null,
          caMainAddressUrl: "www.karlstorz.com",
          buyerProfileUrl: null,
          nutsCodeID: 42,
          nutsCode:
            "System.Data.Entity.DynamicProxies.NUTSCode_547C7532A1C13D2DD8DABA397AFE64934E6300F80287E631C82996E76CE950EB",
          nutsCodeItem: {
            id: 42,
            text: "RO321 Bucuresti",
            localeKey: null,
          },
          contactPerson: null,
          internetAddressesUrl: ["www.karlstorz.com"],
          electronicInfoAccessUrl: null,
          electronicDocumentsSendingUrl: null,
          isSME: false,
          sysNoticeEntityTypeID: 20,
          noticeEntityAddressId: 100437472,
          entityId: 31248,
          entityItem: null,
          isPublishingAgreed: null,
          nationalIDNumber: "RO 22505268",
        },
        source: 3,
      },
      winners: [
        {
          id: 100068340,
          caNoticeId: 100037160,
          name: "KARL STORZ ENDOSCOPIA ROMANIA",
          fiscalNumber: "RO 22505268",
          noticeEntityAddressId: 100437472,
          entityId: 31248,
          isSME: null,
          address: {
            noticeId: null,
            officialName: "KARL STORZ ENDOSCOPIA ROMANIA",
            address: "Strada Colorian Anton, prof. dr., Nr. 74, Sector: 4",
            city: "Bucuresti",
            cityItem: {
              id: 1779,
              text: "Bucuresti",
              localeKey: "",
            },
            postalCode: "041393",
            postalCodeItem: null,
            countryID: 1,
            country: "Romania",
            countryItem: {
              id: 1,
              text: "Romania",
              localeKey: "RO",
            },
            county: {
              id: 4,
              text: "Bucuresti",
              localeKey: "B",
            },
            email: "xxx.xxx@xxx.com; zzz.zzz@zzz.com",
            phone: "+40 xxxx",
            fax: "+40 xxxx",
            contactPoints: null,
            attentionTo: null,
            caMainAddressUrl: "www.karlstorz.com",
            buyerProfileUrl: null,
            nutsCodeID: 42,
            nutsCode:
              "System.Data.Entity.DynamicProxies.NUTSCode_547C7532A1C13D2DD8DABA397AFE64934E6300F80287E631C82996E76CE950EB",
            nutsCodeItem: {
              id: 42,
              text: "RO321 Bucuresti",
              localeKey: null,
            },
            contactPerson: null,
            internetAddressesUrl: ["www.karlstorz.com"],
            electronicInfoAccessUrl: null,
            electronicDocumentsSendingUrl: null,
            isSME: false,
            sysNoticeEntityTypeID: 20,
            noticeEntityAddressId: 100437472,
            entityId: 31248,
            entityItem: null,
            isPublishingAgreed: null,
            nationalIDNumber: "RO 22505268",
          },
          source: 3,
        },
      ],
      lotsCaption:
        "2. Trusa pentru chirurgie laparoscopica si instrumentar pentru Urologie",
      lotsNoCaption: "2",
      contractValue: 319800.0,
      currency: {
        id: 1,
        text: "RON",
        localeKey: "RON",
      },
      defaultCurrencyContractValue: 319800.0,
      currencyRate: 1.0,
      hasElectronicContract: false,
      electronicContractId: null,
      sysElectronicContractStateId: null,
      parentElectronicContractId: null,
      contractValueMinOffer: null,
      contractValueMaxOffer: null,
      defaultCurrencyContractValueMinOffer: null,
      defaultCurrencyContractValueMaxOffer: null,
      hasModifiedVersions: false,
      modifiedCount: 0,
      actions: {
        canEdit: false,
        canView: true,
        canDelete: false,
        canModify: false,
        canOpenContract: false,
        canCreateContract: false,
        canCorrectContract: false,
        canModifyCompetitionResume: false,
      },
      conditions: {
        hasCompetitionResumeSection: false,
      },
      contractType: 1,
    },
    {
      caNoticeContractId: 100063859,
      contractId: null,
      caNoticeId: 100037160,
      noticeNo: "CAN1008830",
      contractNo: "46216",
      contractDate: "2018-11-22T00:00:00+02:00",
      contractTitle: "Contract de furnizare",
      winnerCaption: "MEDIST IMAGING & P.O.C. S.R.L.",
      winner: {
        id: 100068341,
        caNoticeId: 100037160,
        name: "MEDIST IMAGING & P.O.C. S.R.L.",
        fiscalNumber: "RO 24205100",
        noticeEntityAddressId: 100437481,
        entityId: 47982,
        isSME: null,
        address: {
          noticeId: null,
          officialName: "MEDIST IMAGING & P.O.C. S.R.L.",
          address: "Strada Ion Urdareanu, Nr. 34, Sector: 5",
          city: "Bucuresti",
          cityItem: {
            id: 1779,
            text: "Bucuresti",
            localeKey: "",
          },
          postalCode: "050688",
          postalCodeItem: null,
          countryID: 1,
          country: "Romania",
          countryItem: {
            id: 1,
            text: "Romania",
            localeKey: "RO",
          },
          county: {
            id: 4,
            text: "Bucuresti",
            localeKey: "B",
          },
          email: "xxxx@xxxx.ro",
          phone: "+40 xxxxxx",
          fax: "+40 xxxxxx",
          contactPoints: null,
          attentionTo: null,
          caMainAddressUrl: "www.medist-imaging.ro",
          buyerProfileUrl: null,
          nutsCodeID: 42,
          nutsCode:
            "System.Data.Entity.DynamicProxies.NUTSCode_547C7532A1C13D2DD8DABA397AFE64934E6300F80287E631C82996E76CE950EB",
          nutsCodeItem: {
            id: 42,
            text: "RO321 Bucuresti",
            localeKey: null,
          },
          contactPerson: null,
          internetAddressesUrl: ["www.medist-imaging.ro"],
          electronicInfoAccessUrl: null,
          electronicDocumentsSendingUrl: null,
          isSME: false,
          sysNoticeEntityTypeID: 20,
          noticeEntityAddressId: 100437481,
          entityId: 47982,
          entityItem: null,
          isPublishingAgreed: null,
          nationalIDNumber: "RO 24205100",
        },
        source: 3,
      },
      winners: [
        {
          id: 100068341,
          caNoticeId: 100037160,
          name: "MEDIST IMAGING & P.O.C. S.R.L.",
          fiscalNumber: "RO 24205100",
          noticeEntityAddressId: 100437481,
          entityId: 47982,
          isSME: null,
          address: {
            noticeId: null,
            officialName: "MEDIST IMAGING & P.O.C. S.R.L.",
            address: "Strada Ion Urdareanu, Nr. 34, Sector: 5",
            city: "Bucuresti",
            cityItem: {
              id: 1779,
              text: "Bucuresti",
              localeKey: "",
            },
            postalCode: "050688",
            postalCodeItem: null,
            countryID: 1,
            country: "Romania",
            countryItem: {
              id: 1,
              text: "Romania",
              localeKey: "RO",
            },
            county: {
              id: 4,
              text: "Bucuresti",
              localeKey: "B",
            },
            email: "xxxx@xxx.ro",
            phone: "+40 xxxxxx",
            fax: "+40 xxxxxx",
            contactPoints: null,
            attentionTo: null,
            caMainAddressUrl: "www.medist-imaging.ro",
            buyerProfileUrl: null,
            nutsCodeID: 42,
            nutsCode:
              "System.Data.Entity.DynamicProxies.NUTSCode_547C7532A1C13D2DD8DABA397AFE64934E6300F80287E631C82996E76CE950EB",
            nutsCodeItem: {
              id: 42,
              text: "RO321 Bucuresti",
              localeKey: null,
            },
            contactPerson: null,
            internetAddressesUrl: ["www.medist-imaging.ro"],
            electronicInfoAccessUrl: null,
            electronicDocumentsSendingUrl: null,
            isSME: false,
            sysNoticeEntityTypeID: 20,
            noticeEntityAddressId: 100437481,
            entityId: 47982,
            entityItem: null,
            isPublishingAgreed: null,
            nationalIDNumber: "RO 24205100",
          },
          source: 3,
        },
      ],
      lotsCaption:
        "4. Ecograf cu trei sonde pentru Explorari functionale/1 buc",
      lotsNoCaption: "4",
      contractValue: 157400.0,
      currency: {
        id: 1,
        text: "RON",
        localeKey: "RON",
      },
      defaultCurrencyContractValue: 157400.0,
      currencyRate: 1.0,
      hasElectronicContract: false,
      electronicContractId: null,
      sysElectronicContractStateId: null,
      parentElectronicContractId: null,
      contractValueMinOffer: null,
      contractValueMaxOffer: null,
      defaultCurrencyContractValueMinOffer: null,
      defaultCurrencyContractValueMaxOffer: null,
      hasModifiedVersions: false,
      modifiedCount: 0,
      actions: {
        canEdit: false,
        canView: true,
        canDelete: false,
        canModify: false,
        canOpenContract: false,
        canCreateContract: false,
        canCorrectContract: false,
        canModifyCompetitionResume: false,
      },
      conditions: {
        hasCompetitionResumeSection: false,
      },
      contractType: 1,
    },
  ],
}
