import { transformItem, transformPublicNotice, transformNoticeContracts } from "../transformers.js"
import { item, notice, contracts } from "./test-data"

describe("transformers", () => {
  it("shoud transform item", () => {
    const result = {
      caNoticeId: 100066869,
      noticeId: 100174450,
      procedureId: 100045278,
      noticeNo: "CAN1031498",
      sysNoticeTypeId: 3,
      sysNoticeState: {
        id: 2,
        text: "Publicat",
        localeKey: null,
      },
      sysProcedureState: {
        id: 5,
        text: "Atribuita",
        localeKey: null,
      },
      contractingAuthorityNameAndFN: "RO1590120 - REGIA NATIONALA A PADURILOR - ROMSILVA RA",
      nationalId: 1590120,
      contractTitle: "servicii de exploatare masa lemnoasa si transport lemn fasonat DSSV-I",
      sysAcquisitionContractType: {
        id: 2,
        text: "Servicii",
        localeKey: null,
      },
      sysProcedureType: {
        id: 1,
        text: "Licitatie deschisa",
        localeKey: null,
      },
      sysContractAssigmentType: {
        id: 1,
        text: "Contract de achizitii publice",
        localeKey: null,
      },
      cpvCodeAndName: "77211100-3 - Servicii de exploatare forestiera (Rev.2)",
      cpvCode: "77211100-3",
      ronContractValue: 12130675.84,
      noticeStateDate: "2020-04-04T01:54:35+03:00",
      hasSubsequentContracts: false,
      isUtility: false,
      isPPP: false,
      currencyCode: "RON",
    }

    expect(transformItem(item)).toEqual(result)
  })

  it("should transform publicNotice", () => {
    const result = {
      isUtilityContract: false,
      caNoticeEdit_New: {
        publicationDetailsModel: {
          caPublicationDate: "2018-12-10T09:24:07+02:00",
          publicationDate: "2018-07-18T13:22:23+03:00",
          jouePublicationNumber: "",
          noticeNo: "CN1002546",
        },
        section1_New: {
          section1_1: {
            caAddress: {
              noticeId: 100114690,
              officialName: "SPITALUL CLINIC JUDETEAN DE URGENTA SF. APOSTOL ANDREI",
              address: "Strada: Tomis, nr. 145",
              city: "Constanta",
              cityItem: null,
              postalCode: "900591",
              postalCodeItem: null,
              countryID: 1,
              country: "Romania",
              countryItem: {
                id: 1,
                text: "Romania",
                localeKey: "RO",
              },
              county: null,
              caMainAddressUrl: "www.spitalulconstanta.ro",
              buyerProfileUrl: "www.e-licitatie.ro",
              nutsCodeItem: {
                id: 28,
                text: "RO223 Constanta",
                localeKey: null,
              },
              internetAddressesUrl: ["www.spitalulconstanta.ro"],
              electronicInfoAccessUrl: null,
              isSME: false,
              sysNoticeEntityTypeID: 1,
              noticeEntityAddressId: 100437403,
              entityId: 560,
              entityItem: null,
              isPublishingAgreed: null,
              nationalIDNumber: "4301103",
              nationalIDNumberInt: 4301103,
            },
          },
        },
        section2_New: {
          section2_1_New: {
            contractTitle:
              "Furnizarea si instalarea urmatoarelor echipamente medicale: Videolaringoscop pentru sectia ATI Adulti,  Trusa de chirurgie laparoscopica si instrumentar pentru Urologie, Spirometre pentru Explorari Functionale, Ecograf cu trei sonde pentru Explorari functionale si Electrocardiografe portabile/5 Loturi",
            referenceNumber: "26932/09.07.2018",
            mainCPVCode: {
              id: 12677,
              text: "Echipamente medicale (Rev.2)",
              localeKey: "33100000-1",
            },
            sysAcquisitionContractType: {
              id: 1,
              text: "Furnizare",
              localeKey: "Common.Clasiff.SysAcquisitionContractType.Supply",
            },
            shortDescription:
              "Furnizarea si instalarea urmatoarelor echipamente medicale: videolaringoscop pentru sectia ATI Adulti/lot 1, Trusa de chirurgie laparoscopica si instrumentar pentru Urologie/Lot 2, Spirometre pentru Explorari Functionale/Lot 3, Ecograf cu trei sonde pentru Explorari functionale/ Lot 4 si Electrocardiografe portabile/Lot 5.\n\nValoarea contractului de furnizare pentru fiecare LOT in parte:\nLot 1 - videolaringoscop - 50672,26 Lei\nLot 2 - trusa de chirurgie laparoscopica si instrumentar pentru Urologie - 322100,84 Lei \nLot 3 - spirometre pentru Explorari Functionale/2 buc - 20588,23Lei\nLot 4 - ecograf cu trei sonde pentru Explorari Functionale - 168319,32 Lei \nLot 5 - electrocardiografe portabile/6 buc - 72184,86Lei \nValoarea totala a celor 5 loturi este de 633865,51 Lei\nDetaliile fiecarui lot se regasesc in Caietul de sarcini.\nGarantia de participare reprezinta 1% din valoarea fara TVA pentru fiecare LOT ofertat\nTermenul limita pana la care se pot solicita clarificari la documentatia de atribuire: cu 13 zile inainte de data limita de depunere a ofertelor . In conformitate cu prevederile art.161 din legea 98/2016, autoritatea contractanta va raspunde in mod clar si complet solicitarilor de clarificare/informtiilor suplimentare in legatura cu documentatia de atribuire in a 10 a zi inainte de termenul limita stabilit pentru depunerea ofertelor in anuntul de participare",
            hasLots: true,
            numberOfLots: null,
            totalAcquisitionValue: 477200.0,
            totalRONAcquisitionValueForPAAP: 477200.0,
            lowestOffer: 0.0,
            highestOffer: 0.0,
            currency: {
              id: 1,
              text: "Leu",
              localeKey: "RON",
            },
          },
          section2_2_New: {
            descriptionList: [
              {
                noticeLotID: 100188111,
                contractTitle: "Videolaringoscop pentru ATI Adulti",
                lotNumber: "1",
                mainCPVCodes: {
                  id: 12677,
                  text: "33100000-1 Echipamente medicale (Rev.2)",
                  localeKey: null,
                },
                secondaryCPVCodes: [],
                nutsCode: {
                  id: 28,
                  text: "RO223 Constanta",
                  localeKey: null,
                },
                mainLocation: "SCJU Constanta",
                shortDescription:
                  "Videolaringoscop pentru ATI Adulti/1 buc. Descrierea lotului se regaseste in Caietul de sarcini",
                isEUFunded: false,
                euProject: null,
                supplementaryInformation:
                  "Valoarea totala a lotului este de 50672,26. Garantia de participare reprezinta 1% din valoarea totala a lotului.",
                monthDuration: 6,
                dayDuration: null,
                startDate: null,
                completionDate: null,
                showSysAwardCriteriaType: true,
                sysAwardCriteriaTypeId: 2,
                sysAwardCriteriaType: {
                  id: 2,
                  text: "Cel mai bun raport calitate – pret",
                  localeKey: null,
                },
                sysFinancingType: {
                  id: 2,
                  text: "Fonduri bugetare",
                  localeKey: null,
                },
                estimatedValue: 50672.26,
                minEstimatedValue: null,
                maxEstimatedValue: null,
                currency: {
                  id: 1,
                  text: "Leu",
                  localeKey: null,
                },
                lotInfo: "Anulat",
              },
              {
                noticeLotID: 100188113,
                contractTitle: "Electrocardiografe portabile /6 buc",
                lotNumber: "5",
                mainCPVCodes: {
                  id: 12677,
                  text: "33100000-1 Echipamente medicale (Rev.2)",
                  localeKey: null,
                },
                secondaryCPVCodes: [],
                nutsCode: {
                  id: 28,
                  text: "RO223 Constanta",
                  localeKey: null,
                },
                mainLocation: "SCJU Constanta",
                shortDescription:
                  "Electrocardiografe portabile /6 buc. Descrierea lotului se regaseste in Caietul de sarcini",
                isEUFunded: false,
                euProject: null,
                supplementaryInformation:
                  "Valoarea totala a lotului este de 72184,86. Garantia de participare reprezinta 1% din valoarea totala a lotului.",
                monthDuration: 6,
                dayDuration: null,
                startDate: null,
                completionDate: null,
                showSysAwardCriteriaType: true,
                sysAwardCriteriaTypeId: 2,
                sysAwardCriteriaType: {
                  id: 2,
                  text: "Cel mai bun raport calitate – pret",
                  localeKey: null,
                },
                sysFinancingType: {
                  id: 2,
                  text: "Fonduri bugetare",
                  localeKey: null,
                },
                estimatedValue: 72184.86,
                minEstimatedValue: null,
                maxEstimatedValue: null,
                currency: {
                  id: 1,
                  text: "Leu",
                  localeKey: null,
                },
                lotInfo: "Anulat",
              },
            ],
          },
        },
      },
      title:
        "Furnizarea si instalarea urmatoarelor echipamente medicale: Videolaringoscop pentru sectia ATI Adulti,  Trusa de chirurgie laparoscopica si instrumentar pentru Urologie, Spirometre pentru Explorari Functionale, Ecograf cu trei sonde pentru Explorari functionale si Electrocardiografe portabile/5 Loturi",
      caNoticeID: 100037160,
      isPPP: false,
      noticeID: 100114690,
      previousPublicationNoticeID: 100045478,
      previousPublicationNoticeNumber: null,
      sysContractAssignmentTypeID: 1,
      sysNoticeState: {
        id: 2,
        text: "Publicat",
        localeKey: "Common.Clasiff.SysNoticeState.Published",
      },
      sysNoticeType: {
        id: 3,
        text: "Anunt de atribuire",
        localeKey: "Common.Clasiff.SysNoticeType.ContractAwardNotice",
      },
      prevPubSysNoticeType: {
        id: 2,
        text: "Anunt de participare",
        localeKey: "Common.Clasiff.SysNoticeType.ContractNotice",
      },
      contractingAuthorityType: {
        id: 18,
        text: "Organism de drept public",
        localeKey: "Common.Clasiff.ContractingAuthorityType.BodyGuvernedByLow",
      },
      sysNoticeVersion: {
        id: 2,
        text: "Formulare in format > 2016",
        localeKey: "Common.Clasiff.SysNoticeVersion.NewFormat",
      },
      procedureId: 100012670,
      entityId: 560,
      procedureType: {
        id: 1,
        text: "Licitatie deschisa",
        localeKey: null,
      },
      noticeNumber: "CAN1008830",
      procedureHasLots: false,
      publicationDate: "2018-12-10T09:24:07+02:00",
    }

    expect(transformPublicNotice(notice)).toEqual(result)
  })

  it("should transform contracts", () => {
    const result = {
      total: 2,
      items: [
        {
          caNoticeContractId: 100063850,
          contractId: null,
          caNoticeId: 100037160,
          noticeNo: "CAN1008830",
          contractNo: "46218",
          contractDate: "2018-11-22T00:00:00+02:00",
          contractTitle: "Contract de furnizare",
          winnerCaption: "KARL STORZ ENDOSCOPIA ROMANIA",
          winner: {
            id: 100068340,
            caNoticeId: 100037160,
            name: "KARL STORZ ENDOSCOPIA ROMANIA",
            fiscalNumber: "RO 22505268",
            fiscalNumberInt: 22505268,
            noticeEntityAddressId: 100437472,
            entityId: 31248,
            isSME: null,
            address: {
              noticeId: null,
              officialName: "KARL STORZ ENDOSCOPIA ROMANIA",
              address: "Strada Colorian Anton, prof. dr., Nr. 74, Sector: 4",
              city: "Bucuresti",
              cityItem: {
                id: 1779,
                text: "Bucuresti",
                localeKey: "",
              },
              postalCode: "041393",
              postalCodeItem: null,
              countryID: 1,
              country: "Romania",
              countryItem: {
                id: 1,
                text: "Romania",
                localeKey: "RO",
              },
              county: {
                id: 4,
                text: "Bucuresti",
                localeKey: "B",
              },
              caMainAddressUrl: "www.karlstorz.com",
              buyerProfileUrl: null,
              nutsCodeID: 42,
              nutsCodeItem: {
                id: 42,
                text: "RO321 Bucuresti",
                localeKey: null,
              },
              internetAddressesUrl: ["www.karlstorz.com"],
              electronicInfoAccessUrl: null,
              electronicDocumentsSendingUrl: null,
              isSME: false,
              sysNoticeEntityTypeID: 20,
              noticeEntityAddressId: 100437472,
              entityId: 31248,
              entityItem: null,
              isPublishingAgreed: null,
              nationalIDNumber: "RO 22505268",
              nationalIDNumberInt: 22505268,
            },
            source: 3,
          },
          winners: [
            {
              id: 100068340,
              caNoticeId: 100037160,
              name: "KARL STORZ ENDOSCOPIA ROMANIA",
              fiscalNumber: "RO 22505268",
              fiscalNumberInt: 22505268,
              noticeEntityAddressId: 100437472,
              entityId: 31248,
              isSME: null,
              address: {
                noticeId: null,
                officialName: "KARL STORZ ENDOSCOPIA ROMANIA",
                address: "Strada Colorian Anton, prof. dr., Nr. 74, Sector: 4",
                city: "Bucuresti",
                cityItem: {
                  id: 1779,
                  text: "Bucuresti",
                  localeKey: "",
                },
                postalCode: "041393",
                postalCodeItem: null,
                countryID: 1,
                country: "Romania",
                countryItem: {
                  id: 1,
                  text: "Romania",
                  localeKey: "RO",
                },
                county: {
                  id: 4,
                  text: "Bucuresti",
                  localeKey: "B",
                },
                caMainAddressUrl: "www.karlstorz.com",
                buyerProfileUrl: null,
                nutsCodeID: 42,
                nutsCodeItem: {
                  id: 42,
                  text: "RO321 Bucuresti",
                  localeKey: null,
                },
                internetAddressesUrl: ["www.karlstorz.com"],
                electronicInfoAccessUrl: null,
                electronicDocumentsSendingUrl: null,
                isSME: false,
                sysNoticeEntityTypeID: 20,
                noticeEntityAddressId: 100437472,
                entityId: 31248,
                entityItem: null,
                isPublishingAgreed: null,
                nationalIDNumber: "RO 22505268",
                nationalIDNumberInt: 22505268,
              },
              source: 3,
            },
          ],
          lotsCaption: "2. Trusa pentru chirurgie laparoscopica si instrumentar pentru Urologie",
          lotsNoCaption: "2",
          contractValue: 319800.0,
          currency: {
            id: 1,
            text: "RON",
            localeKey: "RON",
          },
          defaultCurrencyContractValue: 319800.0,
          currencyRate: 1.0,
          hasElectronicContract: false,
          electronicContractId: null,
          sysElectronicContractStateId: null,
          parentElectronicContractId: null,
          contractValueMinOffer: null,
          contractValueMaxOffer: null,
          defaultCurrencyContractValueMinOffer: null,
          defaultCurrencyContractValueMaxOffer: null,
          contractType: 1,
        },
        {
          caNoticeContractId: 100063859,
          contractId: null,
          caNoticeId: 100037160,
          noticeNo: "CAN1008830",
          contractNo: "46216",
          contractDate: "2018-11-22T00:00:00+02:00",
          contractTitle: "Contract de furnizare",
          winnerCaption: "MEDIST IMAGING & P.O.C. S.R.L.",
          winner: {
            id: 100068341,
            caNoticeId: 100037160,
            name: "MEDIST IMAGING & P.O.C. S.R.L.",
            fiscalNumber: "RO 24205100",
            fiscalNumberInt: 24205100,
            noticeEntityAddressId: 100437481,
            entityId: 47982,
            isSME: null,
            address: {
              noticeId: null,
              officialName: "MEDIST IMAGING & P.O.C. S.R.L.",
              address: "Strada Ion Urdareanu, Nr. 34, Sector: 5",
              city: "Bucuresti",
              cityItem: {
                id: 1779,
                text: "Bucuresti",
                localeKey: "",
              },
              postalCode: "050688",
              postalCodeItem: null,
              countryID: 1,
              country: "Romania",
              countryItem: {
                id: 1,
                text: "Romania",
                localeKey: "RO",
              },
              county: {
                id: 4,
                text: "Bucuresti",
                localeKey: "B",
              },
              caMainAddressUrl: "www.medist-imaging.ro",
              buyerProfileUrl: null,
              nutsCodeID: 42,
              nutsCodeItem: {
                id: 42,
                text: "RO321 Bucuresti",
                localeKey: null,
              },
              internetAddressesUrl: ["www.medist-imaging.ro"],
              electronicInfoAccessUrl: null,
              electronicDocumentsSendingUrl: null,
              isSME: false,
              sysNoticeEntityTypeID: 20,
              noticeEntityAddressId: 100437481,
              entityId: 47982,
              entityItem: null,
              isPublishingAgreed: null,
              nationalIDNumber: "RO 24205100",
              nationalIDNumberInt: 24205100,
            },
            source: 3,
          },
          winners: [
            {
              id: 100068341,
              caNoticeId: 100037160,
              name: "MEDIST IMAGING & P.O.C. S.R.L.",
              fiscalNumber: "RO 24205100",
              fiscalNumberInt: 24205100,
              noticeEntityAddressId: 100437481,
              entityId: 47982,
              isSME: null,
              address: {
                noticeId: null,
                officialName: "MEDIST IMAGING & P.O.C. S.R.L.",
                address: "Strada Ion Urdareanu, Nr. 34, Sector: 5",
                city: "Bucuresti",
                cityItem: {
                  id: 1779,
                  text: "Bucuresti",
                  localeKey: "",
                },
                postalCode: "050688",
                postalCodeItem: null,
                countryID: 1,
                country: "Romania",
                countryItem: {
                  id: 1,
                  text: "Romania",
                  localeKey: "RO",
                },
                county: {
                  id: 4,
                  text: "Bucuresti",
                  localeKey: "B",
                },
                caMainAddressUrl: "www.medist-imaging.ro",
                buyerProfileUrl: null,
                nutsCodeID: 42,
                nutsCodeItem: {
                  id: 42,
                  text: "RO321 Bucuresti",
                  localeKey: null,
                },
                internetAddressesUrl: ["www.medist-imaging.ro"],
                electronicInfoAccessUrl: null,
                electronicDocumentsSendingUrl: null,
                isSME: false,
                sysNoticeEntityTypeID: 20,
                noticeEntityAddressId: 100437481,
                entityId: 47982,
                entityItem: null,
                isPublishingAgreed: null,
                nationalIDNumber: "RO 24205100",
                nationalIDNumberInt: 24205100,
              },
              source: 3,
            },
          ],
          lotsCaption: "4. Ecograf cu trei sonde pentru Explorari functionale/1 buc",
          lotsNoCaption: "4",
          contractValue: 157400.0,
          currency: {
            id: 1,
            text: "RON",
            localeKey: "RON",
          },
          defaultCurrencyContractValue: 157400.0,
          currencyRate: 1.0,
          hasElectronicContract: false,
          electronicContractId: null,
          sysElectronicContractStateId: null,
          parentElectronicContractId: null,
          contractValueMinOffer: null,
          contractValueMaxOffer: null,
          defaultCurrencyContractValueMinOffer: null,
          defaultCurrencyContractValueMaxOffer: null,
          contractType: 1,
        },
      ],
    }

    expect(transformNoticeContracts(contracts)).toEqual(result)
  })
})
